### ISSUE TITLE
Rust implem

### ISSUE THREAD

**Issue by jerive** [ssbc/bipf#17]
Hello,

I don't know if it is the good place for this, but I just wanted to let you know that I started an implementation of [bipf in rust](https://github.com/jerive/bipf-rs). It is just a toy project for me to learn rust, so there is certainly a lot of room for improvement, but so far I observe a x2/x3 perf gain on both serialization and deserialization. 

Looking forward to hearing from you,

Jerome

**Comment by arj03** [comment]
That sounds great @jerive :)

**Comment by staltz** [comment]
Hey @jerive that's amazing that you are contributing with a Rust implementation of BIPF. Are you interested in using node-bindgen or Neon to make it run in Node.js too? That would provide us a way to test bipf-rs in production in SSB apps, and see if the performance boost is worth it.

I should also mention that I'm updating the tests in BIPF to have a larger coverage and I found some issues with BIPF's implementation, so be careful that this reference implementation may be buggy. I also intend to try to implement BIPF in Zig, but I don't know if I'll manage.

**Comment by jerive** [comment]
Hi @staltz , sure, that was my next step once I finish the base implem :)

Although I was wondering, from my current understanding, at least in a typical SSB workflow, there must be more IO between jitdb <-> bipf than between jitdb <-> outside JS world, and by a significant order of magnitude, so could we really draw any conclusion from such a test ?

Anyways we need to change the current JSON API, so I'm on it.
Thanks for the heads up about the tests, I will fix on my side.

**Comment by jerive** [comment]
So it is a rather big disappointment so far for neon, crossing the rust border seems 

- I implemented encode, decode, seekKey
- Performances are similar in neon and JS for the three functions
- Unless I am mistaken, neon cannot benefit from Buffer optimizations done in JS's seekKey

If you are accustomed to neon and wish to have a look and check on some obvious optimizations I'd have missed, I would be glad.

**Comment by staltz** [comment]
Thank you @jerive for informing that.

I actually got started with implementing BIPF in Zig, which means no FFI. I'm curious how the performance of that will turn out. Are you interested in collaborating on that?

**Comment by jerive** [comment]
It would be amazing!

**Comment by staltz** [comment]
Great! I've been hacking on it locally, I'll get the repo in shape and publish it.

**Comment by staltz** [comment]
Here we go: https://github.com/staltz/bipf-native

The goal is to get all the tests passing, there are already some passing (I think `encode`/`decode` is fully implemented). The tests run in CI too.

**Comment by jerive** [comment]
Runs on my machine too :)
I see createCompareAt test is failing
I will attack this tomorrow.

**Comment by staltz** [comment]
Great! Maybe it's easier to start with `allocAndEncode`. You can run `test-compat/index.js` instead of `test-compat/compare.js`.

**Comment by jerive** [comment]
Ok for you if I start with seekKey/seekPath?

**Comment by jerive** [comment]
> Great! Maybe it's easier to start with `allocAndEncode`. You can run `test-compat/index.js` instead of `test-compat/compare.js`.

Ok!

**Comment by staltz** [comment]
> Ok for you if I start with seekKey/seekPath?

That's also fine :)

**Comment by arj03** [comment]
@jerive I just wanted to let you know that I started a https://github.com/ssbc/bipf-spec repo that includes a link to your implementation. I'll go ahead and close this now :)
