### ISSUE TITLE
Upgrade varint library from 5 to 6 after PR is merged

### ISSUE THREAD

**Issue by Barbarrosa** [ssbc/bipf#21]
The new version includes bounds checking, which is nice. It would be best to wait for the upgrade until https://github.com/chrisdickinson/varint/pull/24 is merged so we can benefit from the `decode` performance optimization.

**Comment by arj03** [comment]
nice performance optimization! :) Do you know what the breaking change is in 6?

**Comment by Barbarrosa** [comment]
@arj03 There's some bounds checking to prevent `NaN` and `Infinity` values from being returned or used by accident, so an error will be thrown in those cases.

**Comment by Barbarrosa** [comment]
I'm wondering if [varint](https://github.com/chrisdickinson/varint) is abandoned now b/c the maintainer hasn't commented on the PR for over a month. The maintainer's still working on other Github projects, though.

**Comment by arj03** [comment]
Latest release is a while ago. Maybe you can try and contact him on mail and see if he's willing to let you commit and do releases. I can help review.

**Comment by Barbarrosa** [comment]
I didn't get an email, but I sent a private message to an account where the maintainer appears to be active. At this point I doubt that I'm going to get a response. Do you have any thoughts about creating an alternate package or embedding the code here?

**Comment by Barbarrosa** [comment]
@arj03 Glad to see that you got an improvement in #37 by unrolling the loop. Did you have a chance to test with the `Math.pow` calls pre-calculated, or do you think that gets optimized?

**Comment by arj03** [comment]
It is actually faster. Thanks :)
