### ISSUE TITLE
decode_reserved

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/bipf#9]
Well, this is a new one:

```
Uncaught ReferenceError: decode_reserved is not defined
    at decode_type (bundle-ui.js:43642)
    at Object.decode (bundle-ui.js:43654)
    at bundle-ui.js:80851
    at bundle-ui.js:122305
    at getData (bundle-ui.js:25412)
    at bundle-ui.js:25423
    at getBlock (bundle-ui.js:25392)
    at get (bundle-ui.js:25421)
    at bundle-ui.js:25583
    at Object.log.get (bundle-ui.js:122301)
```

Evidently in this case, `type` == 7, which I found out by adding a `decode_reserved` function, sticking a breakpoint on it, and walking back up the call stack to `decode_type`.

**Comment by KyleMaas** [comment]
(Oh, and for my own reference in case I need to duplicate this later, this shows up when I click the Threads page of ssb-browser-demo on my normal profile tab.  So that query's the one that triggers this.)

**Comment by arj03** [comment]
Have you been able to reproduce this after you did the multiple tabs thing in browser?

**Comment by KyleMaas** [comment]
Sorry for the delayed response - been a little busy. Because of that busyness, I haven't been active enough with ssb-browser-demo to really know if this is fixed yet.

**Comment by arj03** [comment]
Still would be nice to fix this as its clearly a bug if you hit that somehow

**Comment by staltz** [comment]
dones
